# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Репа",
  "description": "Лучшая репа на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=сочные
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "мой дом не дом и не улица не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    },
    {
      "product": 5,
      "quantity": 243,
      "price": 145
    },
    {
      "product": 4,
      "quantity": 2,
      "price": 200
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/7/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    },
    {
      "product": 5,
      "quantity": 243,
      "price": 145
    },
    {
      "product": 4,
      "quantity": 2,
      "price": 200
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?page=2&products=3
Content-Type: application/json

###

GET {{baseUrl}}/stocks/
Content-Type: application/json
